import type { Player } from "./types"

export const mockPlayers: Player[] = [
  { id: "1", name: "Patrick Mahomes", position: "QB", team: "KC", value: 95 },
  { id: "2", name: "Josh Allen", position: "QB", team: "BUF", value: 92 },
  { id: "3", name: "Lamar Jackson", position: "QB", team: "BAL", value: 90 },
  { id: "4", name: "Joe Burrow", position: "QB", team: "CIN", value: 88 },
  { id: "5", name: "Justin Herbert", position: "QB", team: "LAC", value: 87 },
  { id: "6", name: "Jalen Hurts", position: "QB", team: "PHI", value: 86 },
  { id: "7", name: "Christian McCaffrey", position: "RB", team: "SF", value: 99 },
  { id: "8", name: "Bijan Robinson", position: "RB", team: "ATL", value: 88 },
  { id: "9", name: "Saquon Barkley", position: "RB", team: "PHI", value: 87 },
  { id: "10", name: "Breece Hall", position: "RB", team: "NYJ", value: 86 },
  { id: "11", name: "Jahmyr Gibbs", position: "RB", team: "DET", value: 85 },
  { id: "12", name: "Jonathan Taylor", position: "RB", team: "IND", value: 84 },
  { id: "13", name: "Justin Jefferson", position: "WR", team: "MIN", value: 98 },
  { id: "14", name: "CeeDee Lamb", position: "WR", team: "DAL", value: 95 },
  { id: "15", name: "Tyreek Hill", position: "WR", team: "MIA", value: 94 },
  { id: "16", name: "Ja'Marr Chase", position: "WR", team: "CIN", value: 93 },
  { id: "17", name: "Amon-Ra St. Brown", position: "WR", team: "DET", value: 90 },
  { id: "18", name: "A.J. Brown", position: "WR", team: "PHI", value: 89 },
  { id: "19", name: "Travis Kelce", position: "TE", team: "KC", value: 92 },
  { id: "20", name: "Sam LaPorta", position: "TE", team: "DET", value: 85 },
  { id: "21", name: "T.J. Hockenson", position: "TE", team: "MIN", value: 83 },
  { id: "22", name: "Mark Andrews", position: "TE", team: "BAL", value: 82 },
  { id: "23", name: "George Kittle", position: "TE", team: "SF", value: 81 },
  { id: "24", name: "Dallas Goedert", position: "TE", team: "PHI", value: 79 },
  { id: "25", name: "Derrick Henry", position: "RB", team: "BAL", value: 83 },
  { id: "26", name: "De'Von Achane", position: "RB", team: "MIA", value: 82 },
  { id: "27", name: "Davante Adams", position: "WR", team: "LV", value: 88 },
  { id: "28", name: "Stefon Diggs", position: "WR", team: "HOU", value: 86 },
  { id: "29", name: "Cooper Kupp", position: "WR", team: "LAR", value: 85 },
  { id: "30", name: "Garrett Wilson", position: "WR", team: "NYJ", value: 84 },
]
